# Generated by Django 5.1.6 on 2025-03-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='hashtags',
            field=models.CharField(default='es', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='language',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
