# Generated by Django 5.1.6 on 2025-03-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_hashtags_list_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='hashtags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
